using System;
using UnityEngine;
using TMPro;

public class DailyQuoteManager : MonoBehaviour
{
    [Header("UI")]
    [SerializeField] private TMP_Text exaltationText;
    [SerializeField] private TMP_Text dateText;
    [SerializeField] private TMP_Text quoteTexts;

    [Header("Quotes")]
    [TextArea(3, 8)]
    private string[] exaltations = new string[]
{
"Today is a gift of quiet light that asks nothing from you except presence.",
"The earth continues its gentle promise of life beneath every step you take.",
"This day arrives with silent purpose, already carrying everything it needs.",
"You are standing on a living world that has always been steady beneath you.",
"The sun rises to remind you that every ending quietly becomes a beginning again.",
"Every breath connects you to existence itself in ways you do not need to explain.",
"The sky holds infinite calm above you, unchanged by anything below it.",
"The earth supports you without question, as it always has and always will.",
"Today is another chance to simply be without needing to become anything else.",
"Life continues its sacred rhythm through you even when you are not aware of it.",
"The world is awake in soft harmony, moving without urgency or demand.",
"You are part of something endlessly alive that does not require your permission.",
"The ground beneath you carries ancient strength that has never stopped holding.",
"This moment is held gently by time, without pressure or expectation.",
"Light returns to the world without fail, even after the longest silence.",
"You are surrounded by quiet miracles that do not announce themselves.",
"The earth turns with patient grace, never rushing what is already unfolding.",
"Today unfolds exactly as it should, even if you cannot see the pattern yet.",
"The universe breathes through all things, including the space you occupy right now.",
"You exist within a vast living system that continues whether noticed or not.",
"The sky stretches endlessly in calm witness, holding everything without judgment.",
"Every sunrise is a reminder that renewal is built into the structure of time.",
"The earth gives without expectation, offering life without condition or demand.",
"You are part of nature’s ongoing story that began long before you arrived.",
"Time moves forward with gentle certainty, never asking you to keep pace.",
"The world is full of quiet meaning that does not require translation.",
"You are held by gravity and grace in equal measure every single day.",
"This day is already enough, even before anything is done within it.",
"Life continues beyond all doubt, even when certainty feels far away.",
"The earth remains steady beneath change, absorbing everything without resistance.",
"You are a witness to existence itself unfolding in real time around you.",
"The sun touches everything without discrimination, including what you are becoming.",
"Today carries infinite possibility, even in its simplest ordinary moments.",
"The world is alive with silent energy that does not need to be seen.",
"You belong to this moment completely, without needing to earn your place.",
"The sky reflects endless openness, reminding you that space is always available.",
"The earth remembers how to sustain life even when life feels uncertain.",
"Every moment is a form of creation that does not require effort.",
"You are part of a continuous flow that has never stopped moving forward.",
"The universe expands with quiet certainty, unaffected by hesitation or doubt.",
"Today is not separate from you; it is already part of your existence.",
"The world moves in perfect balance, even when it appears uneven.",
"You are surrounded by natural order that does not need to be controlled.",
"The earth holds space for all life equally, without preference or exclusion.",
"Light returns even after darkness has done its work.",
"You are living proof that continuity exists even through change.",
"The sky watches without judgment, holding everything in equal openness.",
"The earth carries stories older than time, still unfolding beneath your feet.",
"This moment is a small eternity that will never repeat in exactly the same way.",
"You are part of something infinite that does not depend on understanding.",
"The world continues without pause, regardless of attention or awareness.",
"The sun rises whether noticed or not, continuing its steady promise.",
"You are held within existence itself, never outside of it.",
"Every day is a renewal of the earth, whether recognized or not.",
"The universe does not forget to continue, even in silence.",
"You are part of its continuation in ways you may never fully see.",
"The earth moves in quiet devotion, without asking anything in return.",
"Life is unfolding through you as naturally as breath itself.",
"The sky is always above, unchanged in essence no matter the weather.",
"You are grounded in something real that does not depend on feeling.",
"This day is another expression of being alive in a continuous world.",
"The world does not require perfection to continue its quiet existence.",
"You are part of its ongoing balance, already included in its rhythm.",
"The earth is endlessly patient, holding everything without urgency.",
"Light exists even in silence, waiting for nothing to continue.",
"You are a fragment of something whole that is never broken.",
"Time is unfolding gently around you, without pressure or demand.",
"The universe holds you without effort, as if it has always done so.",
"You are never outside of nature, even when you feel distant from it.",
"The world is always becoming, never fixed in a single form.",
"The earth continues its ancient rhythm beneath every change above it.",
"You are present in a living moment that does not need completion.",
"Every breath is shared with the planet that supports it.",
"The sky is wide enough for all things, including uncertainty.",
"You are part of the earth’s memory, carried forward through time.",
"The sun continues its faithful return without hesitation or doubt.",
"The world is never truly still, even in its quietest hours.",
"You exist within motion itself, not outside or apart from it.",
"The earth welcomes every living thing without condition.",
"This day is a quiet beginning that does not require recognition.",
"You are connected to everything around you whether you notice or not.",
"The universe unfolds without resistance, following its own steady rhythm.",
"The earth is both ancient and new in every single moment.",
"You are part of its unfolding story that never stops writing itself.",
"The sky holds space for all change without losing its openness.",
"The world continues its silent work without needing acknowledgment.",
"You are within the rhythm of life that carries all things forward.",
"The earth is a constant presence beneath all temporary uncertainty.",
"Time carries everything forward gently, without rushing what matters.",
"You are part of something unbroken that has never needed repair.",
"The sun brings light without condition, offering itself freely each day.",
"The world exists in quiet harmony that does not require recognition.",
"You are part of its living structure, held within its design.",
"The earth sustains all without asking for anything in return.",
"This moment is held in balance between all that has been and will be.",
"You are inside the flow of time that never pauses or stops.",
"The universe continues to expand without concern for limits.",
"The world remains beautifully alive in every direction at once.",
"You are part of its ongoing creation that never fully ends.",
"The earth continues to offer support without hesitation or fatigue.",
"Light touches everything equally, without preference or exclusion.",
"You are part of a continuous whole that cannot be divided.",
"The sky remains endlessly open, never closing itself to possibility.",
"The world is alive in every direction, even where you are not looking.",
"You are part of its endless motion that carries everything forward.",
"The earth continues without interruption, regardless of observation.",
"This day exists exactly as it is meant to, without correction needed.",
"You are part of its unfolding presence in every passing second.",
"The universe is quietly complete even as it continues to expand.",
"The world is always enough, even before anything is added to it.",
"You are within its ongoing existence, never outside of it.",
"The earth holds everything together without effort or strain.",
"Light continues to return each day with patient reliability.",
"You are part of its renewal that happens without announcement.",
"The sky is constant and infinite, never changing its essence.",
"The world is alive with meaning that does not need explanation.",
"You are part of its living pulse that continues without interruption.",
"The earth continues its silent offering of stability and presence.",
"This moment is fully present, requiring nothing more to complete it.",
"You are part of something greater that includes everything you see.",
"The universe continues its gentle motion without urgency or fear.",
"The world is endlessly sustained by forces beyond interruption.",
"You are part of its quiet order that holds everything together.",
"The earth remains steady and alive beneath every shifting surface.",
"Light continues without end, never exhausting its own presence.",
"You are part of its continuous light that never fully disappears.",
"The sky stretches beyond understanding, holding everything without limit.",
"The world is always in motion, even when it appears still.",
"You are part of its living cycle that never truly breaks.",
"The earth continues its patient existence through every passing age.",
"This day is part of something eternal that does not end here.",
"You are inside the flow of being that never stops unfolding.",
"The universe holds everything together without strain or separation.",
"The world continues to unfold in ways both seen and unseen.",
"You are part of its unfolding reality that never closes.",
"The earth is always present, even when unnoticed or unspoken.",
"Light returns without fail, continuing its quiet promise.",
"You are part of its returning light that never forgets its path.",
"The sky remains open and vast, unchanged by passing moments.",
"The world continues to exist fully in every direction.",
"You are part of its living continuity that never pauses.",
"The earth sustains life constantly without interruption or hesitation.",
"This moment is part of eternity, quietly embedded in time.",
"You are within its ongoing presence that never disappears.",
"The universe continues its quiet expansion beyond all boundaries.",
"The world remains alive and whole in every unfolding second.",
"You are part of its quiet expansion that never stops growing.",
"The earth continues its endless cycle without beginning or end.",
"Light is always returning, even when it feels distant.",
"You are part of its returning cycle that never fails.",
"The sky remains unchanged in essence, no matter what passes below.",
"The world continues its silent movement through all things.",
"You are part of its movement that carries everything forward.",
"The earth is steady beneath all change, holding without effort.",
"This day is part of continuous time that never breaks.",
"You are within its continuity that holds all moments together.",
"The universe continues without pause, never ceasing its expansion.",
"The world is always unfolding into what it already is.",
"You are part of its unfolding motion that never stops.",
"The earth continues to support all life without exception.",
"Light remains a constant presence through every passing moment.",
"You are part of its constant presence that never fades.",
"The sky holds infinite space that never reaches its limit.",
"The world continues in balance even when unseen.",
"You are part of its balance that quietly sustains all things.",
"The earth remains alive and present in every direction.",
"This moment continues endlessly within the flow of time.",
"You are part of its endless continuation without interruption.",
"The universe is always becoming, never finished or fixed.",
"The world is always alive in every possible form.",
"You are part of its living becoming that never ends.",
"The earth continues its quiet existence beneath all motion.",
"Light continues to exist even when not perceived.",
"You are part of its existence that never disappears.",
"The sky remains forever open, never closing or limiting.",
"The world continues its existence without condition.",
"You are part of its continuity of being that never breaks.",
"The earth holds everything gently without resistance.",
"This day continues forward without needing direction.",
"You are part of its forward motion that never stops.",
"The universe continues to hold everything without effort.",
"The world remains steady in motion through all things.",
"You are part of its steady motion that never falters.",
"The earth continues to support you without asking anything back.",
"Light continues to touch all things without exception.",
"You are part of its touch that connects everything together.",
"The sky remains vast and open, holding endless space.",
"The world continues to breathe in quiet rhythm.",
"You are part of its breath that sustains all life.",
"The earth continues its quiet work without recognition.",
"This moment continues to exist without needing approval.",
"You are part of its existence that flows through everything.",
"The universe continues its endless flow without interruption.",
"The world remains whole in every unfolding direction.",
"You are part of its wholeness that cannot be divided.",
"The earth continues without stopping, steady and alive.",
"Light continues its journey through all time and space.",
"You are part of its journey that never reaches an end.",
"The sky remains above everything, constant and open.",
"The world continues its path through endless becoming.",
"You are part of its path that leads through all things.",
"The earth continues its cycle of life without pause.",
"This day continues its presence through every moment.",
"You are part of its presence that never fades away.",
"The universe continues its unfolding without final form.",
"The world is always present, always existing fully.",
"You are part of its present moment that never ends.",
"The earth continues to exist fully in every form.",
"Light continues to exist fully without limitation.",
"You are part of its full existence that never diminishes.",
"The sky remains endlessly present through all change.",
"The world continues endlessly without boundary or limit.",
"You are part of its endlessness that cannot be measured.",
"The earth continues its gentle motion without force.",
"This moment is ongoing, never truly completed.",
"You are part of its ongoing nature that never resolves.",
"The universe continues its being without beginning or end.",
"The world is always being, always alive in motion.",
"You are part of its being that exists without effort.",
"The earth continues its quiet presence without interruption.",
"Light continues without limit through all things.",
"You are part of its limitlessness that expands endlessly.",
"The sky remains open always, without closure or end.",
"The world continues its openness through every change.",
"You are part of its openness that never closes.",
"The earth continues to sustain all life without pause.",
"This day is sustained by forces beyond sight or measure.",
"You are part of its sustenance that never fails.",
"The universe continues to expand endlessly without stopping.",
"The world remains endlessly alive in every direction.",
"You are part of its endless life that continues forever.",
"The earth continues its eternal rhythm without disruption.",
"Light continues eternally through all passing time.",
"You are part of its eternity that never begins or ends.",
"The sky remains eternal, unchanged by all movement below.",
"The world continues eternally in quiet balance.",
"You are part of its eternal flow that never stops.",
"The earth continues without end, steady and complete.",
"This moment is without end, existing beyond measurement.",
"You are part of its endless moment that never closes.",
"The universe continues forever without hesitation or pause.",
"The world continues forever in constant becoming.",
"You are part of its forever that never disappears.",
"The earth continues to be, simply and completely.",
"Light continues to be, without condition or limit.",
"You are part of existence itself, continuous and whole.",
"The sky is not a limit but an invitation to see further.",
"The world is and will always be, in every form it takes.",
"You are you, complete in this moment without addition.",
"The morning holds a place for you in every beginning.",
"Every season knows how to return and begin again in its own time.",
"The silence between moments is also alive and meaningful.",
"You carry only what you choose, and nothing more is required.",
"The horizon is always ahead of you, never behind.",
"What was difficult is already becoming lighter with time.",
"The world has room for your presence exactly as you are.",
"You have arrived exactly where you are meant to be right now.",
"The quiet is not emptiness but space waiting to be noticed.",
"The day does not ask you to be more than you already are.",
"Everything you need is already within reach, even if unseen.",
"The stars do not compete with one another, yet all shine fully.",
"You are allowed to take up space without explanation.",
"The river does not worry about its direction, it simply flows.",
"Something new is always forming within you, quietly and steadily.",
"The morning does not carry yesterday’s weight into today.",
"You are more resilient than you remember in moments of doubt.",
"The world continues to make room for you as you grow.",
"Each step forward is enough, even if it feels small.",
"The light does not hesitate at the threshold of each day.",
"You are already becoming who you need to be, even now.",
"The earth does not rush spring, yet it always arrives.",
"Your presence is a form of contribution simply by existing.",
"What you carry today will feel lighter in time.",
"The sky does not withhold its blue from anyone who looks up.",
"You are allowed to rest and still continue moving forward.",
"The roots grow even when nothing is visible above ground.",
"You are exactly where growth happens, even if unseen.",
"The world is patient with your pace and timing.",
"Something within you already knows how to endure.",
"The light finds its way through even the smallest openings.",
"You do not need to earn the right to experience this day.",
"The tide returns to shore without needing permission.",
"Your life is a form of quiet meaning unfolding over time.",
"The earth blooms without announcement or expectation.",
"You are worthy of the peace you are seeking.",
"Every morning is a practice in beginning again.",
"The wind carries no grudges from what has passed.",
"You are not behind; you are exactly where you need to be.",
"The world is generous with its mornings and its chances.",
"You already have everything you need to face today.",
"The oak does not apologize for taking up space and time.",
"You are a living answer to questions you have not asked yet.",
"The fog always lifts in time, even when it feels permanent.",
"Your story is still being written with care and patience.",
"The seed does not doubt what it will become in time.",
"You belong to the rhythm of living things everywhere.",
"The morning light has no favorites but reaches everything equally.",
"You are allowed to begin again as many times as needed.",
"The earth does not forget how to grow and renew itself.",
"You are here, and that is already enough for this moment.",
"The waves keep returning to the shore without fail.",
"You are built for more than you currently realize.",
"The clouds pass and the sky remains steady behind them.",
"Your quiet moments are not empty or wasted in any way.",
"The garden does not bloom all at once but in its own timing.",
"You are learning in every breath, even when unaware of it.",
"The night always releases into morning without exception.",
"Something good is finding its way toward you gradually.",
"The mountain does not move, and neither must you always.",
"You are held in a web of living things that support you.",
"The rain comes to replenish the earth, not to burden it.",
"You have survived every difficult day that came before this one.",
"The forest does not grow in a hurry, yet it becomes vast.",
"Your softness is also a form of strength and resilience.",
"The sun does not ask permission before it shines each day.",
"You are allowed to take this day slowly without guilt.",
"The earth is older than all your worries combined.",
"You carry light within you that you have not yet discovered.",
"The seasons prove that change is survivable and natural.",
"Your calmness can be a gift to both yourself and others.",
"The river knows how to find the sea without being told.",
"You are not lost; you are still on your way forward.",
"The morning does not owe anything, yet it still gives freely.",
"You are richer in experience than you often feel.",
"The earth does not withhold its beauty from anyone.",
"You are made of the same matter as stars and galaxies.",
"The world is alive because you are here within it.",
"Your breath is proof that you belong in this moment.",
"The light always returns after even the longest nights.",
"You are capable of more gentleness than you believe.",
"The earth does not panic when seasons begin to change.",
"You are allowed to grow at your own pace and rhythm.",
"The morning sky holds no record of what came before.",
"You are free to begin again at this very moment.",
"The world is quietly supporting your becoming.",
"Your presence changes the space around you in subtle ways.",
"The tide does not resist the pull of the moon above.",
"You are part of something that will outlast every worry.",
"The earth forgives and continues to grow without hesitation.",
"You are not alone in your experience of being alive.",
"The stars existed long before any fear or doubt appeared.",
"You are more than the sum of your hardest days.",
"The morning always arrives without exception or delay.",
"You are the continuation of something ancient and ongoing.",
"The world holds space for your becoming without condition.",
"You are allowed to feel at home within your own life.",
"The earth is generous with its patience and time.",
"You are part of a long and living story unfolding.",
"The universe has always made room for you to exist.",
"Today is yours; begin it in your own way.",
"The earth is always turning toward light in its own rhythm.",
"You are held in the hands of something gentle and vast.",
"This day is a small act of grace unfolding around you.",
"You are not separate from the beauty of the world around you.",
"The morning returns because returning is part of light’s nature.",
"You are alive in a world that continues to sustain you.",
"The earth will carry you if you allow it to.",
"You are welcome in this day without condition or hesitation.",
"The sky is open, and so is the possibility within you.",
"Today is the continuation of something worth continuing.",
"You are here, fully present in this unfolding moment.",
"You are yourself, and that is enough for today.",
"Begin now, without waiting for anything else.",
"This is enough, exactly as it is."
};


    [Header("Testing")]
     private string[] quotes = new string[]
    {
        // 1-50
        "Small steps taken daily build the life you imagined.",
        "What you practice in quiet, you become in the open.",
        "The present moment is the only place anything happens.",
        "You do not need to be certain to begin.",
        "Stillness is not the absence of action, it is its source.",
        "Your attention is the most powerful thing you own.",
        "Rest is not retreat, it is preparation.",
        "Clarity comes to those who keep going through confusion.",
        "The life you want is built from ordinary days.",
        "Discipline is remembering what you actually want.",
        "Do not wait to feel ready. Ready is a myth.",
        "Your future self is shaped by today's small choices.",
        "Every expert was once a beginner who kept going.",
        "The work itself is the reward.",
        "Comparison steals the joy from your own path.",
        "Be curious about your life, not critical of it.",
        "Patience is not passive. It is active trust.",
        "You can be both imperfect and enough.",
        "The version of you that tried is worth celebrating.",
        "Focus on the process and the outcome will follow.",
        "Your energy flows where your attention goes.",
        "A single honest conversation changes everything.",
        "You are allowed to outgrow old versions of yourself.",
        "The obstacle you face is also the way forward.",
        "Not every day will feel like progress. Keep going.",
        "How you treat yourself sets the standard for everything.",
        "Courage is not the absence of fear, it is action despite it.",
        "You become what you repeatedly do.",
        "The question is not if you can, but if you will.",
        "Give your best to what matters most.",
        "Gratitude is not a feeling, it is a practice.",
        "Small consistent efforts outlast dramatic bursts.",
        "Your mindset is the environment where ideas grow.",
        "Choose depth over speed.",
        "You grow most at the edge of your comfort.",
        "Listen more than you speak. Learn more than you assume.",
        "Let your actions be louder than your intentions.",
        "What you resist, you carry. What you face, you release.",
        "The mind that is at peace sees clearly.",
        "Invest in what cannot be taken from you.",
        "Not all progress is visible. Trust the unseen work.",
        "You are allowed to change your mind.",
        "Simplicity on the other side of complexity is wisdom.",
        "Do one thing with complete attention today.",
        "You are not your worst day.",
        "Kindness is never wasted, even when unreturned.",
        "Your story is worth telling and living.",
        "Begin before you are ready and learn on the way.",
        "The best time to start was then. The second best is now.",
        "Let go of what is finished. Make room for what is next.",
        // 51-100
        "Your potential is not fixed. It is growing.",
        "The things that challenge you are reshaping you.",
        "A day lived intentionally is a day well spent.",
        "You are exactly where your choices have brought you.",
        "Make peace with the pace of your growth.",
        "Show up fully for the life you already have.",
        "What you give freely tends to return generously.",
        "Clarity of purpose removes the need for urgency.",
        "The strongest foundation is built in ordinary time.",
        "Speak to yourself the way you would to a friend.",
        "Your past is a lesson, not a life sentence.",
        "Trust the version of you that keeps showing up.",
        "Meaning is found in how you engage, not what you possess.",
        "Every thought you choose is a small act of creation.",
        "Peace of mind is built one honest choice at a time.",
        "You are more capable than your doubt suggests.",
        "The goal is not perfection. It is genuine effort.",
        "Progress hides inside consistency.",
        "You are allowed to want things and work toward them.",
        "Take nothing for granted. It all has weight.",
        "Your character is built when no one is watching.",
        "A life of meaning is assembled from small moments.",
        "Fear shrinks when you walk toward it.",
        "You cannot control outcomes, only your effort and response.",
        "What matters most rarely makes the most noise.",
        "Let your values lead the way.",
        "You are the author of your next chapter.",
        "Stop waiting for the right moment. Create it.",
        "Every act of self-discipline is an act of self-respect.",
        "The world rewards persistence more than perfection.",
        "Difficult things get easier with honest practice.",
        "Your words carry more weight than you think.",
        "Ownership of your choices is the beginning of freedom.",
        "You do not need everyone's approval to move forward.",
        "Time spent in reflection is never wasted.",
        "Do not confuse motion with progress.",
        "Your habits are voting for the person you are becoming.",
        "Let the discomfort teach you something.",
        "Decide, then do. Do not linger in between.",
        "Connection is built in small, consistent moments.",
        "You are most powerful when you are most honest.",
        "The long game is the only game worth playing.",
        "What you build quietly is often the most lasting.",
        "Give yourself permission to try and fail and try again.",
        "Real growth rarely looks dramatic from the inside.",
        "You teach people how to treat you by how you treat yourself.",
        "Your energy is finite. Choose where it goes.",
        "Accountability to yourself is a form of respect.",
        "The right path is rarely the easiest one.",
        "You are capable of far more than you currently believe.",
        // 101-150
        "Act as if the outcome matters. Because it does.",
        "Your thoughts are rehearsals for your actions.",
        "The person you want to be is built, not born.",
        "Do less better rather than more carelessly.",
        "Let results speak louder than promises.",
        "The day you plant the seed is not the day you eat the fruit.",
        "You are enough, and you can still become more.",
        "Spend more time doing and less time planning to do.",
        "The cost of inaction is always higher than you expect.",
        "Your future will thank you for what you start today.",
        "Stay humble enough to keep learning.",
        "Every hard conversation you avoid compounds with time.",
        "Where you place your energy determines what grows.",
        "You are not defined by your struggles, but by your response.",
        "Purpose turns ordinary work into something meaningful.",
        "You grow by expanding into what is uncomfortable.",
        "A rested mind solves problems faster than a tired one.",
        "The quality of your questions determines the quality of your life.",
        "Surround yourself with people who challenge and support you.",
        "Act with intention, not just reaction.",
        "Your discipline today is your freedom tomorrow.",
        "You are not competing with anyone but yesterday's version of yourself.",
        "The most important relationship you have is with yourself.",
        "Build something today you will be proud of tomorrow.",
        "What you do consistently is who you are.",
        "The smallest act of kindness ripples further than you know.",
        "Clarity is a practice, not a permanent state.",
        "Your struggles are not a detour. They are the road.",
        "Growth is not always comfortable. That is the point.",
        "You have more agency than you currently use.",
        "Be the kind of person you would want to know.",
        "The voice that says you cannot is not always telling the truth.",
        "Slow down to see what is actually in front of you.",
        "Your choices now are shaping the options you will have later.",
        "Ambition without intention is just noise.",
        "Take the next step. The one after will become visible.",
        "You are more than what you produce.",
        "The things worth having take longer than you want.",
        "Honesty with yourself is the foundation of change.",
        "Do the thing that will matter in five years.",
        "You are capable of holding complexity without breaking.",
        "The effort you give in private builds the life you live in public.",
        "Let your standard be internal, not external.",
        "Every ending contains the beginning of something else.",
        "You have survived difficult things. You will again.",
        "The present moment is the only place your power lives.",
        "Invest in your mind as faithfully as in your body.",
        "What you do today either opens or closes a door tomorrow.",
        "Make your word mean something.",
        "You are allowed to rest without guilt.",
        // 151-200
        "The best version of you already knows what to do.",
        "Do not outsource your thinking to your fears.",
        "You are exactly capable enough for today's challenge.",
        "The gap between who you are and who you want to be is effort.",
        "Do not let the perfect be the enemy of the good.",
        "Your consistency is more powerful than your talent.",
        "You were not meant to figure it all out at once.",
        "Trust the process even when you cannot see the result.",
        "Every great thing began as someone's quiet decision.",
        "The person who gets back up wins.",
        "Do not postpone living.",
        "Your perspective is valuable. Offer it.",
        "What you practice in the morning shapes the whole day.",
        "Let your choices reflect your values, not your moods.",
        "You have always found a way. Remember that.",
        "The pain of growth is different from the pain of stagnation.",
        "Nothing of value is built in a single day.",
        "You are the product of every effort you have made.",
        "Make room for silence. Answers live there.",
        "Every moment of attention is a gift to something.",
        "Your limitations are often just untested assumptions.",
        "Do not be too proud to ask for help.",
        "The version of you that persists is the one that wins.",
        "Ownership is the first step toward change.",
        "You are the one who decides what today means.",
        "Let your effort reflect what you believe you deserve.",
        "You cannot steer a parked car. Start moving.",
        "What gets measured gets managed. What gets managed gets better.",
        "Your habits are the invisible architecture of your life.",
        "The life you dream of is assembled one day at a time.",
        "You are the average of what you repeatedly choose.",
        "Solve for today and tomorrow starts to solve itself.",
        "You are not too late. You are exactly on time.",
        "What you resist will persist. What you face will pass.",
        "Real confidence comes from keeping promises to yourself.",
        "Your next chapter does not have to look like the last.",
        "The effort is the reward before the reward arrives.",
        "You are building something whether you realize it or not.",
        "Every skill you own was once beyond your ability.",
        "You do not need to see the whole staircase. Take the next step.",
        "Silence your inner critic long enough to act.",
        "What you repeat becomes true for you.",
        "Breathe. Then decide. Then act.",
        "You are exactly where you are supposed to be growing.",
        "The only failure is stopping.",
        "Momentum is built by starting, not by waiting to start.",
        "Your purpose does not require an audience.",
        "You are worth the effort you put into yourself.",
        "Every lesson that hurt you also taught you.",
        "Show up. That is always enough to begin.",
        // 201-250
        "The mind is a garden. Choose what you water.",
        "You hold more power in your choices than you know.",
        "One focused hour beats ten distracted ones.",
        "The roots of tomorrow grow in today's soil.",
        "Be the person who finishes what they start.",
        "Your vision will clarify as you move toward it.",
        "You deserve the energy you freely give to others.",
        "The best investment is in your own growth.",
        "Do not wait for motivation. Build it through action.",
        "You are the most consistent thing in your own story.",
        "What you believe about yourself tends to become true.",
        "The work is simple. Doing it consistently is the challenge.",
        "You are not too much. You are not too little.",
        "Embrace the learning curve. That is where growth is.",
        "The right answer often requires sitting with uncertainty.",
        "You are building resilience in real time.",
        "Let the hard days make you more, not less.",
        "Every good habit is a vote for a better future.",
        "You have the tools. Use them.",
        "The world does not need a perfect version of you.",
        "Excellence is a direction, not a destination.",
        "Your instincts know more than your doubts admit.",
        "Tend to the seeds of your best intentions.",
        "You are more than capable of handling what comes.",
        "The day you decide is the day everything changes.",
        "What feels impossible now will feel different in a year.",
        "You carry the wisdom of every hard thing you have lived.",
        "Action is the antidote to anxiety.",
        "You are not stuck. You are in transition.",
        "The difference between where you are and where you want to be is practice.",
        "Do not underestimate the power of showing up twice.",
        "Your effort is the one variable you fully control.",
        "The mind grows strongest when challenged with intention.",
        "You are allowed to take your time and still arrive.",
        "What you give your full attention to, flourishes.",
        "Progress is not always felt. It is always happening.",
        "You are more than your productivity.",
        "Every act of courage leaves the world slightly braver.",
        "You do not need permission to become who you are.",
        "The discipline you build now becomes the freedom you enjoy later.",
        "You are already doing better than you give yourself credit for.",
        "The moment you stop comparing is the moment you start living.",
        "Let the day be what it is and bring your best to it.",
        "You have everything it takes to take the next step.",
        "Your life is the longest story you will ever tell.",
        "Make it one worth reading.",
        "You are not a finished product. That is a good thing.",
        "Every day lived fully is a day worth having lived.",
        "The world grows better when you grow intentionally.",
        "You are a work in progress, and that is exactly right.",
        // 251-300
        "The answer is usually one more honest effort.",
        "You are capable of choosing differently starting now.",
        "What you put in comes back in ways you did not expect.",
        "Your character is revealed in how you handle difficulty.",
        "The light at the end of the tunnel is always real.",
        "You are not the voice that doubts you. You are the one who acts anyway.",
        "The person who keeps going writes the better story.",
        "You have outlasted harder days than this one.",
        "What you commit to becomes what you are known for.",
        "The best gift you can give yourself is honesty.",
        "You are never too old to set another goal.",
        "The road is long enough for rest and still enough for arrival.",
        "Your effort today is a letter to your future self.",
        "Do the next right thing. That is always enough.",
        "You are not supposed to have it all figured out yet.",
        "The strength you need already lives inside you.",
        "Doing your best looks different every day. That is fine.",
        "You are the only one who can show up in your life.",
        "What you are building now will matter more than you think.",
        "Let today be better than yesterday by just one thing.",
        "You are stronger than the story your fear tells.",
        "The moment of discomfort is often the moment of growth.",
        "You have the ability to begin again at any moment.",
        "What you practice in private you perform in public.",
        "Every kind act sends a signal to the universe.",
        "You are more prepared than you feel.",
        "The path forward is lit one step at a time.",
        "Your resilience is not coincidence. You built it.",
        "What looks like an end is often a redirection.",
        "You are allowed to evolve beyond your old limits.",
        "The ground is always solid beneath a steady step.",
        "Your dreams are valid. Your effort is required.",
        "You are here. That is the beginning of everything.",
        "The quiet work is what eventually becomes the loud result.",
        "You are not waiting to be found. You are being built.",
        "Clarity follows commitment. Commit first.",
        "You are worthy of the effort it takes to become.",
        "Today is a chance to do what yesterday was not.",
        "The difficulty is where the meaning is hidden.",
        "You are growing in ways that will surprise you.",
        "Act from your values and the outcome will take care of itself.",
        "The only person you have to be better than is who you were.",
        "You are allowed to be proud of what you have made of your days.",
        "Every challenge carries the lesson you needed.",
        "You are the ongoing answer to every difficulty you have faced.",
        "What matters most is never the result, but who you became.",
        "You are enough. And you can always choose to become more.",
        "Today is a good day to do one thing that matters.",
        "You are not behind. You are becoming.",
        "One honest step forward is always enough.",
        // 301-365
        "You are always closer than you feel.",
        "The person who tries imperfectly beats the one who waits.",
        "You are not doing this alone, even when it feels that way.",
        "The obstacle is the lesson. Learn it and move.",
        "You have what it takes because you have made it this far.",
        "The version of you five years from now is grateful today.",
        "Do not let perfection prevent participation.",
        "Your effort plants the seeds that patience grows.",
        "You are the author of more of your life than you admit.",
        "What you do when it is hard is what defines you.",
        "You are not required to be the same person you were.",
        "The small daily choices are the big life choices.",
        "You are built for this, even on the days you doubt it.",
        "What you return to again and again is what matters to you.",
        "Every setback is a setup for a stronger try.",
        "You are always in the process of becoming.",
        "The day you stop comparing is the day you start arriving.",
        "Your story is still in the middle. Keep going.",
        "You are not behind the curve. You are on your own.",
        "What you give your best to gives its best back.",
        "The courage you need is already inside you.",
        "You are allowed to be hopeful about what comes next.",
        "Not everything will work. Keep going anyway.",
        "You have already done things you once thought impossible.",
        "The most meaningful life is built in the most ordinary moments.",
        "You are your most important project.",
        "Do not chase what drains you. Build what sustains you.",
        "Your growth is the most important investment you will ever make.",
        "You are capable of living a life that feels like yours.",
        "The world needs what only you can bring.",
        "You are more than the limits you have accepted.",
        "What you believe you deserve is what you tend to receive.",
        "You are allowed to rest and still be ambitious.",
        "The life well lived is made of good decisions, repeated.",
        "You are enough. You are ready. Begin.",
        "This is your time. Use it with intention.",
        "You are always one choice away from a different story.",
        "The next right thing is all you ever need to do.",
        "You are here for a reason. Act like it.",
        "Every day is an invitation. Show up for it.",
        "You are capable of depth, growth, and great change.",
        "What you want is possible. What you need is effort.",
        "You are not waiting for your life. This is your life.",
        "The world is better with your full presence in it.",
        "You are becoming. Trust the process.",
        "Do not shrink. Take up the space you were meant to fill.",
        "Your life is a gift to the world when you live it fully.",
        "You are here, alive, and that is extraordinary.",
        "Begin. Then begin again. That is the whole secret.",
        "You are the universe experiencing itself. Make it count.",
        "The day is yours. So is the choice of what to do with it.",
        "You are ready for more than you think.",
        "Let today matter.",
        "You are not finished yet.",
        "The best is still ahead.",
        "Keep going.",
        "You are becoming who you were always meant to be.",
        "Today counts.",
        "You are alive. That is where everything starts.",
        "This moment is yours.",
        "Begin now.",
        "You are here. That is enough to start.",
        "One more day, one more step forward.",
        "You are the protagonist of the only story that matters.",
        "You.",
    };

    [Tooltip("Adds days to today's date. Set to 1 for tomorrow, -1 for yesterday.")]
    [SerializeField] private int dayOffset = 0;

    private int lastOffset;
    private DateTime lastDate;

    private void Start()
    {
        Refresh();
    }

    private void Update()
    {
        if (dayOffset != lastOffset)
        {
            Refresh();
            return;
        }

        DateTime today = GetCurrentDate();
        if (today != lastDate)
        {
            Refresh();
        }
    }

    private DateTime GetCurrentDate()
    {
        return DateTime.Today.AddDays(dayOffset);
    }

    private void Refresh()
    {
        lastOffset = dayOffset;
        lastDate = GetCurrentDate();
        DisplayQuote();
    }

    private void DisplayQuote()
    {
        if (quotes == null || quotes.Length == 0)
        {
            quoteTexts.text = "No quotes available.";
            return;
        }

        if (exaltations == null || exaltations.Length == 0)
        {
            exaltationText.text = "No exaltations available.";
            return;
        }

        int quoteIndex = (lastDate.DayOfYear - 1) % quotes.Length;
        int exaltationIndex = (lastDate.DayOfYear - 1) % exaltations.Length;

        quoteTexts.text = quotes[quoteIndex];
        exaltationText.text = exaltations[exaltationIndex];

        dateText.text = lastDate.ToString("dddd, dd MMMM yyyy");

        Debug.Log($"Date: {lastDate} | Quote index: {quoteIndex} | Exaltation index: {exaltationIndex}");
    }
}